apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: andrewzurn-dot-com
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      labels:
        run.googleapis.com/startupProbeType: Default
      annotations:
        autoscaling.knative.dev/maxScale: '1'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 30
      serviceAccountName: 358151832904-compute@developer.gserviceaccount.com
      containers:
      - image: us.gcr.io/personal-223023/andrewzurn-dot-com:latest
        ports:
        - name: http1
          containerPort: 80
        resources:
          limits:
            cpu: 1000m
            memory: 128Mi
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 80
