baseurl = "https://zurn.dev"
DefaultContentLanguage = "en"
title = "Andrew Zurn"
theme = "beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  homeTitle = "Hi, I'm Andrew" # Set a different text for the header on the home page
  subtitle = "Developer, Teacher, Learner"
  mainSections = ["post","posts"]
  #logo = "img/avatar-icon.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = false
  readingTime = false
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = false
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  name = "Andrew Zurn"
  website = "zurn.dev"
  email = "awzurn@gmail.com"
  github = "AndrewZurn"
  twitter = "AndrewZurn"
  linkedin = "https://www.linkedin.com/in/awzurn"
  strava = "https://www.strava.com/athletes/32967328"

[[menu.main]]
    name = "Home"
    url = "https://zurn.dev"
    weight = 1

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 2

